#!/usr/bin/env bash
set -e


die() {
    echo "$@" >&2
    exit 1
}

post_hooks=()
atexit() {
    for ((i = ${#post_hooks[@]} - 1; i >= 0; i--)) {
        if ! eval "${post_hooks[i]}"; then
            die "WARNING: command failed \"${post_hooks[i]}\""
        fi
    }
}
trap atexit EXIT
run_atexit() {
    post_hooks+=("$*")
}

# get_sym_addr binary symbol
get_sym_addr() {
    local bin="$1"
    local sym="$2"
    local addr
    addr=$(objdump -tT "${bin}" | awk -v sym="${sym}" '$NF == sym && $4 == ".text" {print $1;exit}')
    [[ "$addr" == "" ]] && addr=$(objdump -tT -C "${bin}" | awk -v sym="${sym}" '$NF == sym && $4 == ".text" {print $1;exit}')
    [[ "$addr" == "" ]] && die "missing sym: ${bin}:${sym}"
    (( 0x$addr == 0 )) && die "failed resolve: ${bin}:${sym}"
    addr=0x$(printf "%x" "0x$addr")
    echo "$addr"
}

str_join() {
    IFS="$1"
    shift
    echo "$*"
}
