#!/usr/bin/env bash
set -xe

tracefs="/sys/kernel/debug/tracing"

echo > "$tracefs/set_event"
echo > "$tracefs/kprobe_events"
echo > "$tracefs/uprobe_events"
echo nop > "$tracefs/current_tracer"
echo 0 > "$tracefs/tracing_on"

